In [10]:
# Here we try to segeragate text according to topic!!!

In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('npr.csv')

In [13]:
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [14]:
# df['Article'][4000]
# len(df)

In [83]:
# Remove the stopwords!
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [85]:
df['without_stopwords'] = df['Article'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [86]:
df.head()

Article  \
0  In the Washington of 2016, even when the polic...   
1    Donald Trump has used Twitter  —   his prefe...   
2    Donald Trump is unabashedly praising Russian...   
3  Updated at 2:50 p. m. ET, Russian President Vl...   
4  From photography, illustration and video, to d...   

                                   without_stopwords  
0  In Washington 2016, even policy bipartisan, po...  
1  Donald Trump used Twitter — preferred means co...  
2  Donald Trump unabashedly praising Russian Pres...  
3  Updated 2:50 p. m. ET, Russian President Vladi...  
4  From photography, illustration video, data vis...

In [87]:
from sklearn.feature_extraction.text import CountVectorizer

In [88]:
# max_df --> ignore common words across the document!
cv = CountVectorizer(max_df=0.9, min_df=2)
# min_df --> minimum repeating frequency
# stopwords --. remove the stopwords!

In [89]:
dtm = cv.fit_transform(df['without_stopwords'])

In [90]:
dtm

<11992x55080 sparse matrix of type '<class 'numpy.int64'>'
	with 3549209 stored elements in Compressed Sparse Row format>

In [91]:
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=7, random_state=42)

In [92]:
lda.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

### Grab the vocabulary of the words

In [93]:
len(cv.get_feature_names())

55080

In [94]:
cv.get_feature_names()[5006]

'baseman'

In [95]:
# Get the random words!!!
import random

random_word_id = random.randint(0, 96277)
cv.get_feature_names()[random_word_id]

'practitioner'

### Grab the topics

In [96]:
len(lda.components_)

7

In [97]:
type(lda.components_)

numpy.ndarray

In [98]:
lda.components_.shape

(7, 55080)

In [99]:
lda.components_

array([[3.16528422e+01, 5.82490496e+02, 1.42857148e-01, ...,
        1.42948137e-01, 1.42857148e-01, 1.42861637e-01],
       [5.93571404e+00, 3.62486337e+02, 3.14258498e+00, ...,
        6.14250412e+00, 1.25576550e+00, 1.44699194e-01],
       [1.86026487e+00, 1.60060850e+03, 1.42857147e-01, ...,
        1.42968653e-01, 1.43202940e-01, 1.42857145e-01],
       ...,
       [2.61447184e+00, 1.72865686e+03, 1.42857149e-01, ...,
        1.42894338e-01, 1.42857148e-01, 1.42857146e-01],
       [7.40347369e+00, 8.20554094e+02, 1.42881488e-01, ...,
        1.42895250e-01, 1.02779288e+00, 1.42881756e-01],
       [4.21019613e+01, 1.03455042e+02, 1.43104944e-01, ...,
        1.42930378e-01, 1.44667240e-01, 2.14095924e+00]])

In [100]:
single_topic = lda.components_[0]

In [101]:
single_topic.argsort()

array([26688, 21819, 20167, ..., 37569, 43192, 42759], dtype=int64)

In [102]:
# EXAMPLE FOR ARGSORT()
import numpy as np
arr = np.array([10, 200, 1])
arr

array([ 10, 200,   1])

In [103]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [104]:
# Argsort --> Returns the positions sorted from the least to greatest
# [-10:] --> TOP 10 VALUES (10 GREATEST VALUES)
# Last 10 values of the argsort()
single_topic.argsort()[-10:]

array([41153, 24740, 49866, 26136, 34723, 22729, 36475, 37569, 43192,
       42759], dtype=int64)

In [105]:
top_ten_words = single_topic.argsort()[-20:]

In [106]:
for index in top_ten_words:
    print(cv.get_feature_names()[index])

city
but
npr
department
court
law
they
two
we
also
reports
in
told
it
one
he
people
police
says
said


In [107]:
# Grab the higest probability words per topic

In [108]:
for i, topic in enumerate(lda.components_):
    print(f'THE TOP 15 WORDS FOR THE TOPIC #{i}')
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

THE TOP 15 WORDS FOR THE TOPIC #0
['law', 'they', 'two', 'we', 'also', 'reports', 'in', 'told', 'it', 'one', 'he', 'people', 'police', 'says', 'said']




THE TOP 15 WORDS FOR THE TOPIC #1
['also', 'time', 'and', 'years', 'food', 'world', 'but', 'like', 'new', 'first', 'in', 'he', 'one', 'says', 'it']




THE TOP 15 WORDS FOR THE TOPIC #2
['in', 'there', 'get', 're', 'we', 'like', 'and', 'one', 'health', 'that', 'they', 'but', 'people', 'it', 'says']




THE TOP 15 WORDS FOR THE TOPIC #3
['state', 'republican', 'obama', 'election', 'that', 'and', 'but', 'would', 'he', 'it', 'campaign', 'president', 'clinton', 'said', 'trump']




THE TOP 15 WORDS FOR THE TOPIC #4
['new', 'that', 'also', 'care', 'state', 'but', 'government', 'president', 'health', 'people', 'trump', 'it', 'says', 'would', 'said']




THE TOP 15 WORDS FOR THE TOPIC #5
['that', 'but', 'north', 'one', 'said', 'education', 'in', 'schools', 'company', 'china', 'new', 'it', 'school', 'students', 'says']




THE TOP 15 WORDS F

In [109]:
topic_results = lda.transform(dtm)

In [111]:
topic_results.shape

(11992, 7)

In [112]:
df['Topic'] = topic_results.argmax(axis=1)

In [114]:
df.head(10)

Article  \
0  In the Washington of 2016, even when the polic...   
1    Donald Trump has used Twitter  —   his prefe...   
2    Donald Trump is unabashedly praising Russian...   
3  Updated at 2:50 p. m. ET, Russian President Vl...   
4  From photography, illustration and video, to d...   
5  I did not want to join yoga class. I hated tho...   
6  With a   who has publicly supported the debunk...   
7  I was standing by the airport exit, debating w...   
8  If movies were trying to be more realistic, pe...   
9  Eighteen years ago, on New Year’s Eve, David F...   

                                   without_stopwords  Topic  
0  In Washington 2016, even policy bipartisan, po...      3  
1  Donald Trump used Twitter — preferred means co...      3  
2  Donald Trump unabashedly praising Russian Pres...      3  
3  Updated 2:50 p. m. ET, Russian President Vladi...      4  
4  From photography, illustration video, data vis...      1  
5  I want join yoga class. I hated beatific instr...      2  
6  With publicly supported debunked claim vaccine...      2  
7  I standing airport exit, debating whether get ...      6  
8  If movies trying realistic, perhaps way summon...      2  
9  Eighteen years ago, New Year’s Eve, David Fish...      1